global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alexander_marychev'
