---
- name: Add repo docker
  hosts: all
  become: true

  tasks:
    - name: apt-get update
      apt:
        update_cache: yes

    - name: Install using the repository
      apt: "name={{ item }} state=present"
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu xenial stable

