---
- name: Install docker
  hosts: all
  become: true

  tasks:
    - name: apt-get update
      apt:
        update_cache: yes

    - name: INSTALL DOCKER ENGINE - COMMUNITY
      apt: "name={{ item }} state=present"
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - python-pip

    - name: Install docker
      pip:
        name: docker
